### ISSUE TITLE
OrientdbServiceProvider 

### ISSUE THREAD

**Issue by metehan** [sgpatil/orientdb-laravel-5#1]
Hi,

I added this line to my app.php

```
Sgpatil\Orientdb\OrientdbServiceProvider::class,
```

and get this error, how can i fix it

```
[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Sgpatil\Orientdb\OrientdbServiceProvider' not found
```

**Comment by sgpatil** [comment]
Hi @Metehan , the code is not stable yet. I think above problem occured due to improper folder structure. I have just resolved it. Now you can retry it. It will get install but some functionality may not be working. I am trying to resolve all issues as soon as possible and release the stable version.

**Comment by metehan** [comment]
Hi, @sgpatil thank you. I just updated to latest version and error dissapeared :)
